name: authorization_screen
description: "Auth screen."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^11.1.0
  navigation:
    path: ../../navigation
  flutter_bloc:  ^9.1.1
  equatable: ^2.1.0
  bloc: ^9.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
